x-common-env: &common-env
  env_file: [../.env] 

networks:
  internal:
    external: true
    name: prefect_internal_network

volumes:
  pipeboard-pgdata:

services:
  db:
    image: postgres:14-alpine
    <<: *common-env
    networks: [internal]
    ports:
      - "15432:5432"
    volumes:
      - pipeboard-pgdata:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "max_connections=300"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 30s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    <<: *common-env
    networks: [internal]
    expose: ["6379"]
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  orion:
    build:
      context: ..
      dockerfile: docker/Dockerfile.orion
    image: mrschrodingers/pipeboard-orion:latest 
    hostname: orion
    networks:
      internal:
        aliases:
          - orion
    <<: *common-env
    environment:
      PREFECT_UI_API_URL: "/api"
    ports: ["${HOST_PREFECT_PORT:-4200}:${CONTAINER_PREFECT_PORT:-4200}"]
    volumes:
      - ~/.docker/config.json:/root/.docker/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      db: { condition: service_healthy }
      redis: { condition: service_healthy }
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:${CONTAINER_PREFECT_PORT:-4200}/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 90s

  prefect-setup:
    build:
      context: ..
      dockerfile: docker/Dockerfile.setup
    image: mrschrodingers/pipeboard-setup:latest
    <<: *common-env
    networks: [internal]
    volumes:
      - ~/.docker/config.json:/root/.docker/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      orion: { condition: service_healthy }
    restart: "no"

  worker:
    build:
      context: ..
      dockerfile: infrastructure/prefect/worker/Dockerfile.worker
    image: mrschrodingers/pipeboard-worker:latest
    <<: *common-env
    networks: [internal]
    volumes:
      - ~/.docker/config.json:/root/.docker/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock 
    depends_on:
      orion: { condition: service_healthy }
      prefect-setup: { condition: service_completed_successfully }
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'prefect worker start --pool' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
