scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: pipeboard-services
    static_configs:
      - targets:
          - 'pushgateway:9091'   
          - 'worker:8082'       
