FROM prefecthq/prefect:3.4.1-python3.12

WORKDIR /opt/prefect/app

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential libpq-dev gcc git curl && \
    rm -rf /var/lib/apt/lists/*

COPY pyproject.toml poetry.lock* ./
COPY . .

RUN /opt/prefect/.venv/bin/pip install --no-cache-dir --upgrade pip \
 && /opt/prefect/.venv/bin/pip install --no-cache-dir .

ENV PYTHONPATH=/opt/prefect/app
