TYPES_CLEAN = {
    "access": "JSONB",
    "activated": "BOOLEAN",
    "active": "BOOLEAN",
    "active_flag": "BOOLEAN",
    "activity_count": "SMALLINT",
    "add_time": "TIMESTAMP WITH TIME ZONE",
    "address_admin_area_level_1": "VARCHAR(100)",
    "address_country": "VARCHAR(100)",
    "address_postal_code": "VARCHAR(30)",
    "assigned_to_user_id": "BIGINT",
    "attendees": "JSONB",
    "close_time": "TIMESTAMP WITH TIME ZONE",
    "color": "VARCHAR(30)",
    "company_domain": "TEXT",
    "company_id": "TEXT",
    "company_name": "TEXT",
    "contact_email": "TEXT",
    "contact_name": "TEXT",
    "contact_phone": "TEXT",
    "creator_user_id": "BIGINT",
    "created": "TIMESTAMP WITH TIME ZONE",
    "created_by_user_id": "BIGINT",
    "currency": "VARCHAR(10)",
    "deal_duration_days": "SMALLINT",
    "deal_id": "BIGINT",
    "deal_probability": "INTEGER",
    "default_currency": "TEXT",
    "due_date": "DATE",
    "expected_close_date": "DATE",
    "has_created_company": "BOOLEAN",
    "icon_key": "VARCHAR(100)",
    "icon_url": "TEXT",
    "is_admin": "BOOLEAN",
    "is_deleted": "BOOLEAN",
    "is_you": "BOOLEAN",
    "key_string": "VARCHAR(100)",
    "label_ids": "JSONB",
    "lang": "VARCHAR(10)",
    "last_activity_due_date": "TIMESTAMP WITH TIME ZONE",
    "last_login": "TIMESTAMP WITH TIME ZONE",
    "location": "TEXT",
    "location_formatted_address": "TEXT",
    "lost_time": "TIMESTAMP WITH TIME ZONE",
    "marked_as_done_time": "TIMESTAMP WITH TIME ZONE",
    "modified": "TIMESTAMP WITH TIME ZONE",
    "name": "VARCHAR(255)",
    "note": "TEXT",
    "nº_aviso_de_sinistro_text": "TEXT",
    "org_id": "BIGINT",
    "organization_id": "BIGINT",
    "owner_id": "BIGINT",
    "person_id": "BIGINT",
    "phone": "VARCHAR(50)",
    "picture_id": "BIGINT",
    "pipeline_id": "BIGINT",
    "project_id": "BIGINT",
    "public_description": "TEXT",
    "rotten_flag": "BOOLEAN",
    "role_id": "BIGINT",
    "stage_change_time": "TIMESTAMP WITH TIME ZONE",
    "stage_id": "BIGINT",
    "status": "VARCHAR(50)",
    "timezone_offset": "TEXT",
    "title": "TEXT",
    "update_time": "TIMESTAMP WITH TIME ZONE",
    "update_user_id": "BIGINT",
    "url_title": "VARCHAR(255)",
    "user_id": "BIGINT",
    "value": "NUMERIC(18,4)",
    "value_amount": "NUMERIC(18,4)",
    "value_currency": "VARCHAR(10)",
    "value_per_day": "NUMERIC(18,4)",
    "won_time": "TIMESTAMP WITH TIME ZONE",
    "order_nr": "INTEGER",  
    "participants": "JSONB",
    "custom_fields_overflow": "JSONB"
}
